
import java.util.Stack;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */

import java.util.*;

public class RegisterFrom extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrom
     */
    public int flags=0;
       public String types="NULL";
       public int flag=0;
       public String Location="NULL";
       String Name1="NULL";
    String addr="NULL";
    String desc="NULL";
    String fname="NULL";
    String path="NULL";

    
       LocationForm lf=new LocationForm(this);
      public RegisterFrom() {
          
          
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        radio_action();
        

    }
      public RegisterFrom(String types,String Location,String Name1,String addr,String desc,String path,String fname)
      {
          initComponents();
          this.setLocationRelativeTo(null);
          this.types=types;
          this.Location=Location;
          this.desc=desc;
          this.fname=fname;
          this.path=path;
          
          radio_action();
          
      }
      
      
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            buttonGroup =(javax.swing.ButtonGroup)java.beans.Beans.instantiate(getClass().getClassLoader(), "RegisterFrom_buttonGroup1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ProperSanitation = new javax.swing.JRadioButton();
        WaterSupply = new javax.swing.JRadioButton();
        RoadMaintenance = new javax.swing.JRadioButton();
        NoisePopulation = new javax.swing.JRadioButton();
        PublicTransportation = new javax.swing.JRadioButton();
        Enroachment = new javax.swing.JRadioButton();
        ElectricitySupply = new javax.swing.JRadioButton();
        PublicSafety = new javax.swing.JRadioButton();
        CivicAmenities = new javax.swing.JRadioButton();
        StreetVendors = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        jLabel2.setText("Tyoe Of Complaints : ");

        buttonGroup.add(ProperSanitation);
        ProperSanitation.setText("Proper Sanitation ");
        ProperSanitation.setActionCommand("Option 1");
        ProperSanitation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProperSanitationActionPerformed(evt);
            }
        });

        buttonGroup.add(WaterSupply);
        WaterSupply.setText("Water Supply");
        WaterSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterSupplyActionPerformed(evt);
            }
        });

        buttonGroup.add(RoadMaintenance);
        RoadMaintenance.setText("Road Maintenance");
        RoadMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoadMaintenanceActionPerformed(evt);
            }
        });

        buttonGroup.add(NoisePopulation);
        NoisePopulation.setText("Noise Population");
        NoisePopulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoisePopulationActionPerformed(evt);
            }
        });

        buttonGroup.add(PublicTransportation);
        PublicTransportation.setText("Public Transportation");
        PublicTransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicTransportationActionPerformed(evt);
            }
        });

        buttonGroup.add(Enroachment);
        Enroachment.setText("Enroachment and Illegal Construction");
        Enroachment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnroachmentActionPerformed(evt);
            }
        });

        buttonGroup.add(ElectricitySupply);
        ElectricitySupply.setText("Electricity Supply");
        ElectricitySupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectricitySupplyActionPerformed(evt);
            }
        });

        buttonGroup.add(PublicSafety);
        PublicSafety.setText("Public Safety");
        PublicSafety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicSafetyActionPerformed(evt);
            }
        });

        buttonGroup.add(CivicAmenities);
        CivicAmenities.setText("Civic Amenities ");
        CivicAmenities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CivicAmenitiesActionPerformed(evt);
            }
        });

        buttonGroup.add(StreetVendors);
        StreetVendors.setText("Street Vendors");
        StreetVendors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetVendorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(StreetVendors, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CivicAmenities, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PublicSafety, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ElectricitySupply, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ProperSanitation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Enroachment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PublicTransportation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NoisePopulation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RoadMaintenance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WaterSupply, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(ProperSanitation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaterSupply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RoadMaintenance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoisePopulation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PublicTransportation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Enroachment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ElectricitySupply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PublicSafety)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CivicAmenities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StreetVendors)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(next)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProperSanitationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProperSanitationActionPerformed
        // TODO add your handling code here:
        if(ProperSanitation.isSelected())
        {
            types="Proper Sanitation";
            
        }
    }//GEN-LAST:event_ProperSanitationActionPerformed

    private void WaterSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterSupplyActionPerformed
        // TODO add your handling code here:
        if(WaterSupply.isSelected())
        {
            types="Water Supply";
            
        }
        
    }//GEN-LAST:event_WaterSupplyActionPerformed

    private void CivicAmenitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CivicAmenitiesActionPerformed
        // TODO add your handling code here:
        if(CivicAmenities.isSelected())
        {
            types="Civic Amenities";
            
        }
    }//GEN-LAST:event_CivicAmenitiesActionPerformed

    private void NoisePopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoisePopulationActionPerformed
        // TODO add your handling code here:
        if(NoisePopulation.isSelected())
        {
            types="Noise Population";
            
        }
    }//GEN-LAST:event_NoisePopulationActionPerformed

    private void EnroachmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnroachmentActionPerformed
        // TODO add your handling code here:
        if(Enroachment.isSelected())
        {
            types="Enroachment";
            
        }
    }//GEN-LAST:event_EnroachmentActionPerformed

    private void RoadMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoadMaintenanceActionPerformed
        // TODO add your handling code here:
        if(RoadMaintenance.isSelected())
        {
            types="Road Maintenance";
            
        }
    }//GEN-LAST:event_RoadMaintenanceActionPerformed

    public void radio_action()
    {
        if(types=="Proper Sanitation")
        {
            System.out.println("hi1");
            ProperSanitation.setSelected(true);
        }
        if(types=="Road Maintenance")
        {
            RoadMaintenance.setSelected(true);
        }
        if(types=="Enroachment")
        {
            Enroachment.setSelected(true);
        }
        if(types=="Noise Population")
        {
            NoisePopulation.setSelected(true);
        }
        if(types=="Civic Amenities")
        {
            CivicAmenities.setSelected(true);
        }
        if(types=="Water Supply")
        {
            WaterSupply.setSelected(true);
        }
        if(types=="Public Transportation")
        {
            PublicTransportation.setSelected(true);
        }
        if(types=="Electricity Supply")
        {
            ElectricitySupply.setSelected(true);
        }
        if(types=="Street Vendors")
        {
            StreetVendors.setSelected(true);
        }
        if(types=="Public Safety")
        {
            PublicSafety.setSelected(true);
        }
    }
    
    
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
       LocationForm lf= new LocationForm(types,Location,Name1,addr,desc,path,fname);
                //System.exit(0);
                lf.setVisible(true);
                lf.pack();
                lf.setLocationRelativeTo(null);
                lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
        
        
        
        
      
        
       

        
    }//GEN-LAST:event_nextActionPerformed

    private void PublicTransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicTransportationActionPerformed
        // TODO add your handling code here:
        if(PublicTransportation.isSelected())
        {
            types="Public Transportation";
            
        }
    }//GEN-LAST:event_PublicTransportationActionPerformed

    private void ElectricitySupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectricitySupplyActionPerformed
        // TODO add your handling code here:
        if(ElectricitySupply.isSelected())
        {
            types="Electricity Supply";
            
        }
    }//GEN-LAST:event_ElectricitySupplyActionPerformed

    private void PublicSafetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicSafetyActionPerformed
        // TODO add your handling code here:
        if(PublicSafety.isSelected())
        {
            types="Public Safety";
            
        }
    }//GEN-LAST:event_PublicSafetyActionPerformed

    private void StreetVendorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetVendorsActionPerformed
        // TODO add your handling code here:
        if(StreetVendors.isSelected())
        {
            types="Street Vendors";
            
        }
        
    }//GEN-LAST:event_StreetVendorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
         
        /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new RegisterFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CivicAmenities;
    private javax.swing.JRadioButton ElectricitySupply;
    private javax.swing.JRadioButton Enroachment;
    private javax.swing.JRadioButton NoisePopulation;
    private javax.swing.JRadioButton ProperSanitation;
    private javax.swing.JRadioButton PublicSafety;
    private javax.swing.JRadioButton PublicTransportation;
    private javax.swing.JRadioButton RoadMaintenance;
    private javax.swing.JRadioButton StreetVendors;
    private javax.swing.JRadioButton WaterSupply;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
